wandb_version: 1

batch_size:
  value: 122
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.09713689907814153
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
