wandb_version: 1

batch_size:
  value: 43
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.08959055217485005
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
