wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.052362636206137306
loss:
  value: MeanSquaredError
optimizer:
  value: adam
