wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.9.5
      5: 0.10.33
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 160
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 15
fc_layer_size:
  desc: null
  value: 512
layers:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.06719836936164567
loss:
  desc: null
  value: MeanAbsoluteError
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: loss
optimizer:
  desc: null
  value: adam
parameters:
  desc: null
  value:
    batch_size:
      distribution: q_log_uniform
      max: 5.545177444479562
      min: 3.4657359027997265
      q: 1
    dropout:
      values:
      - 0.3
      - 0.4
      - 0.5
    epochs:
      value: 15
    fc_layer_size:
      values:
      - 128
      - 256
      - 512
    layers:
      values:
      - 2
      - 3
      - 4
    learning_rate:
      distribution: uniform
      max: 0.1
      min: 0
    loss:
      values:
      - MeanSquaredError
      - MeanAbsoluteError
    optimizer:
      values:
      - adam
      - sgd
      - adadelta
      - nadam
