wandb_version: 1

batch_size:
  value: 76
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.00015609114127957958
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
