wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.014609388733027084
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
