wandb_version: 1

batch_size:
  value: 244
conv_layer_size:
  value: 32
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: relu
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.006916895697546466
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
