wandb_version: 1

batch_size:
  value: 177
conv_layer_size:
  value: 64
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.06682594822751772
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
