wandb_version: 1

batch_size:
  value: 113
conv_layer_size:
  value: 16
dropout:
  value: 0.4
epochs:
  value: 10
fc_activation:
  value: relu
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.0541037473723525
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
