wandb_version: 1

batch_size:
  value: 79
conv_layer_size:
  value: 128
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.022561616037868482
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
