wandb_version: 1

batch_size:
  value: 207
conv_layer_size:
  value: 16
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.0820187394599551
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
