wandb_version: 1

batch_size:
  value: 95
conv_layer_size:
  value: 16
dropout:
  value: 0.5
epochs:
  value: 10
fc_activation:
  value: relu
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.01848425034577562
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
