wandb_version: 1

batch_size:
  value: 248
conv_layer_size:
  value: 16
dropout:
  value: 0.5
epochs:
  value: 10
fc_activation:
  value: relu
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.033149795352003776
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
