wandb_version: 1

batch_size:
  value: 52
conv_layer_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.07509538786196303
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
