wandb_version: 1

batch_size:
  value: 255
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.008226721512441571
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
