wandb_version: 1

batch_size:
  value: 46
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: linear
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.033089331903655365
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
