wandb_version: 1

batch_size:
  value: 118
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.01592574163864893
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
