wandb_version: 1

batch_size:
  value: 45
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.09303385647903886
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
