wandb_version: 1

batch_size:
  value: 255
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.027401381734754218
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
