wandb_version: 1

batch_size:
  value: 38
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.03671374716304198
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
