wandb_version: 1

batch_size:
  value: 99
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.04076477874477981
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
