wandb_version: 1

batch_size:
  value: 192
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: linear
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.05226067756767249
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
