wandb_version: 1

batch_size:
  value: 70
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.08741217941637225
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
