wandb_version: 1

batch_size:
  value: 48
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.0398089531692311
loss:
  value: MeanSquaredError
optimizer:
  value: adam
