wandb_version: 1

batch_size:
  value: 39
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.06713151942496798
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
