wandb_version: 1

batch_size:
  value: 80
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.07153361264943214
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
