wandb_version: 1

batch_size:
  value: 33
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.09760636869962797
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
