wandb_version: 1

batch_size:
  value: 37
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.009391665305151798
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
