wandb_version: 1

batch_size:
  value: 145
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.032261892625679
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
