wandb_version: 1

batch_size:
  value: 226
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.07370852269014587
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
