wandb_version: 1

batch_size:
  value: 110
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.007288820870978253
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
