wandb_version: 1

batch_size:
  value: 62
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.009565203226777298
loss:
  value: MeanSquaredError
optimizer:
  value: adam
