wandb_version: 1

batch_size:
  value: 150
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.05274991731129269
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
