wandb_version: 1

batch_size:
  value: 35
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.04212456043186533
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
