wandb_version: 1

batch_size:
  value: 89
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.08455334290714084
loss:
  value: MeanSquaredError
optimizer:
  value: adam
