wandb_version: 1

batch_size:
  value: 46
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: linear
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.09693520177320863
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
