wandb_version: 1

batch_size:
  value: 53
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.08277684158268143
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
