wandb_version: 1

batch_size:
  value: 95
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: linear
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.026596317539038097
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
