wandb_version: 1

batch_size:
  value: 47
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.011133044417237725
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
