wandb_version: 1

batch_size:
  value: 77
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.045286539066260095
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
