wandb_version: 1

batch_size:
  value: 193
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.0465024119791865
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
