wandb_version: 1

batch_size:
  value: 87
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.03761977875367757
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
