wandb_version: 1

batch_size:
  value: 236
dropout:
  value: 0.3
epochs:
  value: 12
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.0058584363076967134
loss:
  value: MeanSquaredError
optimizer:
  value: adam
