wandb_version: 1

batch_size:
  value: 176
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: softmax
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.0997302964837718
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
