wandb_version: 1

batch_size:
  value: 116
dropout:
  value: 0.4
epochs:
  value: 12
fc_activation:
  value: exponential
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.06399457512578988
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
