wandb_version: 1

batch_size:
  value: 40
dropout:
  value: 0.5
epochs:
  value: 12
fc_activation:
  value: relu
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.002707438133781981
loss:
  value: MeanSquaredError
optimizer:
  value: adam
