wandb_version: 1

batch_size:
  value: 46
dropout:
  value: 0.4
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.048325273885260006
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
