wandb_version: 1

batch_size:
  value: 65
dropout:
  value: 0.4
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.06684543834211633
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
