wandb_version: 1

batch_size:
  value: 44
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.027555662052317555
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
