wandb_version: 1

batch_size:
  value: 58
dropout:
  value: 0.4
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.036230985468966616
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
