wandb_version: 1

batch_size:
  value: 45
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.03332432367721202
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
