wandb_version: 1

batch_size:
  value: 61
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.073439122354325
loss:
  value: MeanSquaredError
optimizer:
  value: adam
