wandb_version: 1

batch_size:
  value: 106
conv_layer_size:
  value: 64
dropout:
  value: 0.2
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 1028
layers:
  value: 3
learning_rate:
  value: 0.016028976523607286
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
