wandb_version: 1

batch_size:
  value: 22
conv_layer_size:
  value: 32
dropout:
  value: 0.2
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.022185368424195984
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
