wandb_version: 1

batch_size:
  value: 24
conv_layer_size:
  value: 32
dropout:
  value: 0.4
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.00461728657929818
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
