wandb_version: 1

batch_size:
  value: 60
conv_layer_size:
  value: 16
dropout:
  value: 0.3
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 1028
layers:
  value: 3
learning_rate:
  value: 0.0047598103480635924
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
