wandb_version: 1

batch_size:
  value: 40
conv_layer_size:
  value: 32
dropout:
  value: 0.3
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.024180716457188625
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
