wandb_version: 1

batch_size:
  value: 52
conv_layer_size:
  value: 16
dropout:
  value: 0.4
epochs:
  value: 15
fc_activation:
  value: relu
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.007000092601699082
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
