wandb_version: 1

batch_size:
  value: 165
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.049248478449537794
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
