wandb_version: 1

batch_size:
  value: 47
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.09538717351614073
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
