wandb_version: 1

batch_size:
  value: 43
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.015630940938187923
loss:
  value: MeanSquaredError
optimizer:
  value: adam
