wandb_version: 1

batch_size:
  value: 158
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.09860460425477792
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
