wandb_version: 1

batch_size:
  value: 85
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.04986772002669653
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
