wandb_version: 1

batch_size:
  value: 185
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.08656556392881089
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
