wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.04867621594007702
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
