wandb_version: 1

batch_size:
  value: 195
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.07217610439458705
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
