wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.9.5
      5: 0.10.32
      8:
      - 5
batch_size:
  desc: null
  value: 66
conv_layer_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 15
fc_activation:
  desc: null
  value: relu
fc_layer_size:
  desc: null
  value: 256
layers:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.022205477333765253
loss:
  desc: null
  value: MeanAbsoluteError
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: loss
optimizer:
  desc: null
  value: adam
parameters:
  desc: null
  value:
    batch_size:
      distribution: q_log_uniform
      max: 4.852030263919617
      min: 2.772588722239781
      q: 1
    conv_layer_size:
      values:
      - 16
      - 32
      - 64
    dropout:
      values:
      - 0.2
      - 0.3
      - 0.4
    epochs:
      value: 15
    fc_activation:
      values:
      - relu
    fc_layer_size:
      values:
      - 256
      - 512
      - 1028
    layers:
      values:
      - 2
      - 3
    learning_rate:
      distribution: uniform
      max: 0.05
      min: 0
    loss:
      values:
      - MeanAbsoluteError
    optimizer:
      values:
      - adam
