wandb_version: 1

batch_size:
  value: 42
dropout:
  value: 0.3
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.030395221816613263
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
