wandb_version: 1

batch_size:
  value: 181
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.05588465599478159
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
