wandb_version: 1

batch_size:
  value: 121
conv_layer_size:
  value: 32
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.07689903191372066
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
