wandb_version: 1

batch_size:
  value: 211
conv_layer_size:
  value: 32
dropout:
  value: 0.4
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.07559783801983594
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
