wandb_version: 1

batch_size:
  value: 32
conv_layer_size:
  value: 128
dropout:
  value: 0.3
epochs:
  value: 10
fc_activation:
  value: sigmoid
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.022971987798217675
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
