wandb_version: 1

batch_size:
  value: 43
dropout:
  value: 0.4
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.05182462982727403
loss:
  value: MeanSquaredError
optimizer:
  value: adam
