wandb_version: 1

batch_size:
  value: 95
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.021261359962588402
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
