wandb_version: 1

batch_size:
  value: 49
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.07699760192334137
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
