wandb_version: 1

batch_size:
  value: 86
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.014803008818454089
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
