wandb_version: 1

batch_size:
  value: 36
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.023770960580734826
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
