wandb_version: 1

batch_size:
  value: 77
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.003452948554309121
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
