wandb_version: 1

batch_size:
  value: 109
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.0841896547982201
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
