wandb_version: 1

batch_size:
  value: 43
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.07625121989661156
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
