wandb_version: 1

batch_size:
  value: 45
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.05917622815441986
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
