wandb_version: 1

batch_size:
  value: 66
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.06841710486059348
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
