wandb_version: 1

batch_size:
  value: 65
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.05601997342877383
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
