wandb_version: 1

batch_size:
  value: 57
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.013440227428500762
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
