wandb_version: 1

batch_size:
  value: 226
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.0875140557447836
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
