wandb_version: 1

batch_size:
  value: 249
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.08660459960828837
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
