wandb_version: 1

batch_size:
  value: 49
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.09796472202075661
loss:
  value: MeanSquaredError
optimizer:
  value: adam
