wandb_version: 1

batch_size:
  value: 51
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.06876345167279502
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
