wandb_version: 1

batch_size:
  value: 205
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.046059169245519574
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
