wandb_version: 1

batch_size:
  value: 58
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.08396610867582782
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
