wandb_version: 1

batch_size:
  value: 126
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.052101056057727774
loss:
  value: MeanSquaredError
optimizer:
  value: adam
