wandb_version: 1

batch_size:
  value: 228
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.0394859556228142
loss:
  value: MeanSquaredError
optimizer:
  value: adam
