wandb_version: 1

batch_size:
  value: 48
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.08554412396808299
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
