wandb_version: 1

batch_size:
  value: 90
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.06048288574285515
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
