wandb_version: 1

batch_size:
  value: 100
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.06108787650653974
loss:
  value: MeanSquaredError
optimizer:
  value: adam
