wandb_version: 1

batch_size:
  value: 74
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.04505724084964069
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
