wandb_version: 1

batch_size:
  value: 176
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.0491731681100081
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
