wandb_version: 1

batch_size:
  value: 112
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.07137805756681265
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
