wandb_version: 1

batch_size:
  value: 60
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.07296224296434754
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
