wandb_version: 1

batch_size:
  value: 57
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.09333931471372502
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
