wandb_version: 1

batch_size:
  value: 40
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.05534917764670483
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
