wandb_version: 1

batch_size:
  value: 107
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.09140930332212123
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
