wandb_version: 1

batch_size:
  value: 146
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.006624278798119121
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
