wandb_version: 1

batch_size:
  value: 113
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.018003868773824937
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
