wandb_version: 1

batch_size:
  value: 38
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.039879184217678255
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
