wandb_version: 1

batch_size:
  value: 120
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.007036488679132791
loss:
  value: MeanSquaredError
optimizer:
  value: adam
