wandb_version: 1

batch_size:
  value: 58
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.05484837838522397
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
