wandb_version: 1

batch_size:
  value: 36
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.09259196363499489
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
