wandb_version: 1

batch_size:
  value: 132
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.052165213165984194
loss:
  value: MeanSquaredError
optimizer:
  value: adam
