wandb_version: 1

batch_size:
  value: 247
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.02207996016494085
loss:
  value: MeanSquaredError
optimizer:
  value: adam
