wandb_version: 1

batch_size:
  value: 39
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.04610660013349658
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
