wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.08115077514596405
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
