wandb_version: 1

batch_size:
  value: 142
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.005562652077391384
loss:
  value: MeanSquaredError
optimizer:
  value: adam
