wandb_version: 1

batch_size:
  value: 155
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.01293396626860448
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
