wandb_version: 1

batch_size:
  value: 105
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.07924337749989072
loss:
  value: MeanSquaredError
optimizer:
  value: adam
