wandb_version: 1

batch_size:
  value: 69
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.018071432843520984
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
