wandb_version: 1

batch_size:
  value: 110
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.008259039167734973
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
