wandb_version: 1

batch_size:
  value: 92
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.06899010176542499
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
