wandb_version: 1

batch_size:
  value: 63
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.03075557972752513
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
