wandb_version: 1

batch_size:
  value: 73
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.08270363006542665
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
