wandb_version: 1

batch_size:
  value: 168
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.04572410505614258
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
