wandb_version: 1

batch_size:
  value: 193
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.061765951399177704
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
