wandb_version: 1

batch_size:
  value: 33
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.08862268496180986
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
