wandb_version: 1

batch_size:
  value: 34
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.007034250657953035
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
