wandb_version: 1

batch_size:
  value: 68
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.019514280521651373
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
