wandb_version: 1

batch_size:
  value: 112
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.0148579250993093
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
