wandb_version: 1

batch_size:
  value: 174
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.07334471922526302
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
