wandb_version: 1

batch_size:
  value: 43
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 3
learning_rate:
  value: 0.0654393660479445
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
