wandb_version: 1

batch_size:
  value: 60
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.07930816011772394
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
