wandb_version: 1

batch_size:
  value: 130
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.032394425193003465
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
