wandb_version: 1

batch_size:
  value: 33
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.022461596218347646
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
