wandb_version: 1

batch_size:
  value: 109
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.028368950584243782
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
