wandb_version: 1

batch_size:
  value: 135
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.04812686161685114
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
