wandb_version: 1

batch_size:
  value: 42
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.0916067830253528
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
