wandb_version: 1

batch_size:
  value: 182
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.06941141788591489
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
