wandb_version: 1

batch_size:
  value: 100
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.06688517308309384
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
