wandb_version: 1

batch_size:
  value: 220
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.09709465958248878
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
