wandb_version: 1

batch_size:
  value: 99
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.035898638647205126
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
