wandb_version: 1

batch_size:
  value: 217
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.07299970972235757
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
