wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.05478661865237755
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
