wandb_version: 1

batch_size:
  value: 77
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 3
learning_rate:
  value: 0.021999920316996182
loss:
  value: MeanSquaredError
optimizer:
  value: adam
