wandb_version: 1

batch_size:
  value: 95
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.03741153292037567
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
