wandb_version: 1

batch_size:
  value: 203
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.0385071156531786
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
