wandb_version: 1

batch_size:
  value: 84
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.05007164031827335
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
