wandb_version: 1

batch_size:
  value: 171
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.015030478155772088
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
