wandb_version: 1

batch_size:
  value: 37
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.013942281133839518
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
