wandb_version: 1

batch_size:
  value: 151
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.04706365293018871
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
