wandb_version: 1

batch_size:
  value: 125
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.07927163262402642
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
