wandb_version: 1

batch_size:
  value: 112
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.048040520911252195
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
