wandb_version: 1

batch_size:
  value: 208
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.026303243710216053
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
