wandb_version: 1

batch_size:
  value: 200
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.09190193620068925
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
