wandb_version: 1

batch_size:
  value: 82
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 2
learning_rate:
  value: 0.03320260503059221
loss:
  value: MeanSquaredError
optimizer:
  value: nadam
