wandb_version: 1

batch_size:
  value: 111
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.07847189682422248
loss:
  value: MeanAbsoluteError
optimizer:
  value: nadam
