wandb_version: 1

batch_size:
  value: 146
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.00746832222196604
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
