wandb_version: 1

batch_size:
  value: 92
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.011198676115838425
loss:
  value: MeanAbsoluteError
optimizer:
  value: sgd
