wandb_version: 1

batch_size:
  value: 216
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.05826900626662514
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
