wandb_version: 1

batch_size:
  value: 98
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 4
learning_rate:
  value: 0.07477730368410976
loss:
  value: MeanSquaredError
optimizer:
  value: adam
