wandb_version: 1

batch_size:
  value: 80
dropout:
  value: 0.4
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.03661331532054153
loss:
  value: MeanAbsoluteError
optimizer:
  value: adam
