wandb_version: 1

batch_size:
  value: 69
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.04047280590152627
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
