wandb_version: 1

batch_size:
  value: 157
dropout:
  value: 0.3
epochs:
  value: 15
fc_layer_size:
  value: 256
layers:
  value: 4
learning_rate:
  value: 0.09727445636561993
loss:
  value: MeanAbsoluteError
optimizer:
  value: adadelta
