wandb_version: 1

batch_size:
  value: 39
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 2
learning_rate:
  value: 0.05345924334644923
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
