wandb_version: 1

batch_size:
  value: 42
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 128
layers:
  value: 3
learning_rate:
  value: 0.001297775158197201
loss:
  value: MeanSquaredError
optimizer:
  value: adam
