wandb_version: 1

batch_size:
  value: 42
dropout:
  value: 0.5
epochs:
  value: 15
fc_layer_size:
  value: 512
layers:
  value: 4
learning_rate:
  value: 0.011168900245694802
loss:
  value: MeanSquaredError
optimizer:
  value: adadelta
