wandb_version: 1

batch_size:
  value: 60
dropout:
  value: 0.5
epochs:
  value: 12
fc_layer_size:
  value: 128
layers:
  value: 2
learning_rate:
  value: 0.020307164309054482
loss:
  value: MeanSquaredError
optimizer:
  value: sgd
